### ISSUE TITLE
Change the links to old domain name to be accessible by any domain names

### ISSUE THREAD

**Issue by MaathavanJkr** [kanimaitech/Varaipadavi#13]
Change the links to old domain name vp.kanimai.tech which is down now to be accessible by any domain name.

**Comment by Chris-G-Dev** [comment]
Can I take this issue?

**Comment by Muskan-Malhotra** [comment]
Could you please let me know more about this issue? I am a beginner if I can help you in any way.

**Comment by MaathavanJkr** [comment]
> Could you please let me know more about this issue? I am a beginner if I can help you in any way.

@Muskan-Malhotra Previously the website was hosted in [vp.kanimai.tech](). So the wesite links were dirrected toward the same domain name. Currently the website is hosted in [https://kanimaitech.github.io/Varaipadavi/](). We need to change the links that dirrected towards [vp.kanimai.tech]() to accessible by any domain name change in future.

**Comment by Chris-G-Dev** [comment]
I can take care of this issue. So all links will need https://kanimaitech.github.io/Varaipadavi/ ?

**Comment by MaathavanJkr** [comment]
No they should not direct any domains. Only the pages without the domain
name.

Maathavan

**Comment by Chris-G-Dev** [comment]
Yeah, that's what I meant. Any links that began with vp.kanimai.tech originally now need to begin with https://kanimaitech.github.io/Varaipadavi/

**Comment by MaathavanJkr** [comment]
No they should not define any domains. For example if the link directs [
https://vp.kanimai.tech/study.html]() it should be changed to
[/study.html]() only

Maathavan

**Comment by MaathavanJkr** [comment]
> Yeah, that's what I meant. Any links that began with vp.kanimai.tech originally now need to begin with https://kanimaitech.github.io/Varaipadavi/, but you want it to be setup in the HTML where the links will work no matter the domain.

Yeah you got it. ;) Good luck easy one. ;)

**Comment by Chris-G-Dev** [comment]
The only instance that I found that would need to be changed is in the 404.html file, unless I'm mistaken? Since all the HTML files are in the same folder, just removing the https://vp.kanimai.tech/ before mobile.html and web.html would be the only changes needed.

**Comment by MaathavanJkr** [comment]
Oops, I don't know why I got directed to old domain name when I tried last time. Hmm🤔🤔 something with the hosting ig. Sorry for wasting your time. Change it in 404.html

**Comment by MaathavanJkr** [comment]
#15 Done
