### ISSUE TITLE
Loading icon should be centered

### ISSUE THREAD

**Issue by MaathavanJkr** [kanimaitech/Varaipadavi#14]
Loading Icon is not centered.

**Comment by ankitgauri26** [comment]
@MaathavanJkr - Can I work on it? Please assign it to me

**Comment by MaathavanJkr** [comment]
> @MaathavanJkr - Can I work on it? Please assign it to me

Yeah sure go on. ;)

**Comment by ankitgauri26** [comment]
@MaathavanJkr 
Thank you.
As this is Tamil game, can you guide me the steps to show the loading icon? It will be helpful for me

**Comment by MaathavanJkr** [comment]
> @MaathavanJkr
> Thank you.
> As this is Tamil game, can you guide me the steps to show the loading icon? It will be helpful for me

https://github.com/kanimaitech/Varaipadavi/blob/dbe403a1a746b3607401356c4d695f2ebab1a5cf/web.html#L38

This is the element for loading icon. It is made with CSS. I don't think you need knowledge in Tamil to do this if you need I'm always here to help.

**Comment by MaathavanJkr** [comment]
@ankitgauri26 #18

**Comment by MaathavanJkr** [comment]
#19

**Comment by MaathavanJkr** [comment]
#19 Solved
