### ISSUE TITLE
Remove not used CSS

### ISSUE THREAD

**Issue by MaathavanJkr** [kanimaitech/Varaipadavi#22]
There are some CSS that are not used in the project. Find those and remove.

**Comment by ankitgauri26** [comment]
@MaathavanJkr - Can i work on this? Please assign it to me

**Comment by MaathavanJkr** [comment]
@ankitgauri26 Sure :)

**Comment by ankitgauri26** [comment]
Thank you for assigning it to me.

**Comment by ankitgauri26** [comment]
@MaathavanJkr - Getting error while clicking on Quiz link in the Navbar. Quiz link is referring to web/web.html and web.html is not present in the web folder. Kindly check

**Comment by ankitgauri26** [comment]
@MaathavanJkr - Fixed #22 and generate the PR

**Comment by MaathavanJkr** [comment]
> @MaathavanJkr - Getting error while clicking on Quiz link in the Navbar. Quiz link is referring to web/web.html and web.html is not present in the web folder. Kindly check

Oops should have checked that.
