### ISSUE TITLE
Arrange the files and folders

### ISSUE THREAD

**Issue by MaathavanJkr** [kanimaitech/Varaipadavi#24]
Arrange the files like put css, js and img into assets folder, Change the paths in the script files too. And arrange mobile and web views in seperate folders.

**Comment by MaathavanJkr** [comment]
#25

**Comment by MaathavanJkr** [comment]
@sathyasub do u want me to assign you to this issue?

**Comment by sathyasub** [comment]
@MaathavanJkr yes please

**Comment by MaathavanJkr** [comment]
Good Luck! :)

**Comment by MaathavanJkr** [comment]
@sathyasub oops sorry i merged the pull. but saw the issue now. Login Signup and forgot html files also should be in the root folder. Can you make those changes too?

**Comment by sathyasub** [comment]
@MaathavanJkr Sure.. 404 also should be in root right?

**Comment by MaathavanJkr** [comment]
Yup.

Maathavan

**Comment by MaathavanJkr** [comment]
> @MaathavanJkr Sure.. 404 also should be in root right?
> Can we create new folder for it which stays common to both?

@sathyasub are you working on this? Or can I assign someone else?
